core/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/<int:pk>/edit/", views.ProfileEditView.as_view(), name="profile-edit"),
    path("", include("django.contrib.auth.urls")),
    path("send-email/", views.send_email, name="send-email"),
    path("test/", views.test, name="test"),
    # path('api/v1/',include('accounts.api.v1.urls')),
    path("api/v2/", include("djoser.urls")),
    path("api/v2/", include("djoser.urls.jwt")),
]

core/blog/api/v1/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("post", views.PostModelViewSet, basename="post")
router.register("category", views.CategoryModelViewSet, basename="category")
router.register("comment", views.CommentModelViewSet, basename="comment")
urlpatterns = router.urls


# urlpatterns = [
#     # path('post/',views.postList,name="post-list"),
#     # path('post/<int:id>/',views.postDetail,name="post-detail"),
#     # path('post/',views.PostList.as_view(),name="post-list"),
#     # path('post/<int:pk>/',views.PostDetail.as_view(),name="post-detail"),
#     path('post/',views.PostViewSet.as_view({'get':'list','post':'create'}),name='post-list'),
#     path('post/<int:pk>/',views.PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}),name="post-detail"),
# ]

core/blog/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/api/", views.PostListApiView.as_view(), name="post-list-api"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path(
        "post/<int:pk>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),

    # Cache
    path("test/", views.test, name="test"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse


# from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog Api",
        default_version="v1",
        description="this is a test api for maktabkhooneh project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="bigdeli.ali3@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

from django.views.generic import RedirectView
class indexView(RedirectView):
    pattern_name = 'blog:index'

# def indexView(request):
#     return HttpResponse("<h1>Django Final Test</h1>")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("comment/", include("comment.urls")),
    path("", indexView.as_view(), name="index"),
    path("blog/", include("blog.urls")),
    # path('api-docs/',include_docs_urls(title='api sample')),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# getting user model object
# User = get_user_model()


class Post(models.Model):
    """
    this is a class to define posts for blog app
    """

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE, related_name='upost')
    image = models.ImageField(upload_to='blog/',null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[0:5]

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    """
    this is a class to define categories for blog table
    """

    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "status", "category", "published_date", "image"]

core/blog/api/v1/views.py
from rest_framework.permissions import (
    IsAuthenticated,
    IsAuthenticatedOrReadOnly,
    IsAdminUser,
)
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework.decorators import action
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter

from .paginations import DefaultPagination
from .filters import PostFilters
from .serializers import PostSerializer, CategorySerializer
from ...models import Post, Category
from .permissions import IsOwnerOrReadOnly


from comment.models import Comment
from comment.api.v1.serializers import CommentSerializer


class PostModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    # filterset_fields = {'category':["exact","in"], 'author':["exact"],'status':["exact"]}
    filterset_class = PostFilters
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

class CommentModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination

core/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import (
    ListView,
    DetailView,
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.http import HttpResponse, JsonResponse
from .models import Post
from django.shortcuts import get_object_or_404
from .forms import PostForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)

# test
from django.views import View
from comment.models import Comment
from django.contrib import messages
from comment.forms import CommentForm
from accounts.models import Profile
from accounts.models import User
import requests
# Create your views here.

# Function Base View show a template

class IndexView(TemplateView):
    """
    a class based view to show index page
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        return context


class PostListView(ListView):
    permission_required = "blog.view_post"
    # queryset = Post.objects.all()
    # model = Post
    context_object_name = "posts"
    # paginate_by = 2
    ordering = "-id"
    def get_queryset(self):
        posts = Post.objects.filter(status=True)
        return posts


class PostDetailView(View):
    form_class = CommentForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        commments = Comment.objects.filter(post=self.post_instance.id)
        return render(request, 'blog/blog-single.html',{'post':self.post_instance,'commments':commments, 'form':self.form_class})


    def post(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comments = form.save(commit=False)
            new_comments.user = profile
            new_comments.name = request.user
            new_comments.post = self.post_instance
            new_comments.save()
            messages.success(request, 'your comment submitted successfully', 'success')
            return redirect('blog:post-detail', self.post_instance.id)
        return redirect('blog:post-detail', self.post_instance.id)


class PostListApiView(TemplateView):
    template_name = "blog/post_list_api.html"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.author = profile
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = "/blog/post/"

# @cache_page(60)
# def test(request):
#     response = requests.get("https://5add16cb-13b5-4c3e-ac48-635ec4f8654b.mock.pstmn.io/test/delay/20")
#     return JsonResponse(response.json())

@cache_page(1200)
def test(request):
    api_key = 'c10cf61f23551c490fe69ca601a58502'
    city_name = 'Tehran'
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}&units=metric"

    response = requests.get(url)
    data = response.json()

    if data['cod'] == 200:
        temperature = data['main']['temp']
        weather_description = data['weather'][0]['description']
        print(f"The temperature in {city_name} is {temperature} degrees Celsius with {weather_description}.")
        return JsonResponse(response.json())
    else:
        return HttpResponse("Failed to retrieve weather data.")

    

core/templates/blog/include/blog-all-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
									<h4 class="tagcloud-title">Tag Clouds</h4>
									<ul>
                                        {% for tag in tags.all %}
										<li><a href="{% url 'blog:blog_tag' tag_name=tag.name  %}">{{ tag.name }}</a></li>
                                        {% endfor %}

									</ul>
								</div>

core/templates/blog/include/blog-cat-tag.html
{% if post.tags.count > 0 %}
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
        <li><a href="{% url 'blog:blog_tag' tag_name=tag.name  %}">{{ tag.name }}</a></li>
        {% endfor %}

    </ul>
</div>
{% endif %}

core/templates/blog/include/blog-comments.html
{% load static %}
{% comment %} {% load humanize %} {% endcomment %}

<div class="comments-area">
				
    <h4>{{ comments|length }} Comments</h4>
    
    <div class="comment-list">
    {% for comment in commments %}
    
        <div class="single-comment justify-content-between d-flex">
            <div class="user justify-content-between d-flex">
                <div class="thumb">
                    <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                </div>
                <div class="desc">
                    <h5><a href="#">{{comment.name}}</a></h5>
                    {% comment %} <p class="date">{{comment.created_date|naturalday}} </p> {% endcomment %}
                    <p class="date">{{comment.created_date}} </p>
                    <p class="comment">
                        {{comment.message}}
                    </p>
                </div>
            </div>
            <!--
            <div class="reply-btn">
                <a href="" class="btn-reply text-uppercase">reply</a>
            </div>
            -->
        </div>
        {% empty %}
        <div class="single-comment justify-content-between d-flex">
        <p class="center"> no comments here be the first one to tell your thoughts </p>
    </div>
    {% endfor %}
</div>
</div>

<div class="comment-form">
    <h4>Leave a Comment</h4>
        <form action="" method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="post" value={{post.id}}>
        {% if request.user.is_authenticated %}
        <input type="hidden" name="name" value={{request.user.first_name}}>
        <input type="hidden" name="email" value={{request.user.email}}>
        {% else %}
        <div class="form-group form-inline">
            <div class="form-group col-lg-6 col-md-12 name">
                <input type="text" class="form-control" name="name" placeholder="Enter Name"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
            </div>
            <div class="form-group col-lg-6 col-md-12 email">
                <input type="email" class="form-control" name="email" placeholder="Enter email address"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
            </div>
        </div>
        {% endif %}
        <div class="form-group">
            <input type="text" class="form-control" name="subject" placeholder="Subject"
                onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
        </div>
        <div class="form-group">
            <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
                onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                required=""></textarea>
        </div>
        <button type="submit" class="primary-btn text-uppercase">Post Comment</button>
    </form>
    {% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-error">
<h4>Please fix the following errors</h4>
<ul>
{% for field in form %}
  {% if field.errors %}
    {% for error in field.errors %}
      <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
    {% endfor %}
  {% endif %}
{% endfor %}
</ul>
{% if form.non_field_errors %}
{{ form.non_field_errors }}
{% endif %}
</div>
{% endif %}
</div>

core/templates/blog/include/blog-comments2.html
{% if request.user.is_authenticated %}
<div class="comments-area">
							<div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://127-0-0-1-8000-1tm8fzg0vs.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
							</div>

<div class="comment-form">

							</div>

{% endif %}

core/templates/blog/include/blog-navigation-area.html
{% load static %}
<div class="navigation-area">
    <div class="row">

        {% if  post.get_previous_by_updated_at %}
        <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
            <div class="thumb">

                <a href="{% url 'blog:single' post_id=post.id  %}"><img class="img-fluid" src="" alt=""></a>
            </div>
            <div class="arrow">
                <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
            </div>
            <div class="detials">
                <p>Prev Post</p>
                <a href="#"><h4>Sace The Final Frontier</h4></a>
            </div>
        </div>
        {% endif %}

        {% if  post.get_next_by_updated_at %}
        <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
            <div class="detials">
                <p>Next Post</p>
                <a href="{% url 'blog:single' post_id=post.id %}"><h4>Telescopes 101</h4></a>
            </div>
            <div class="arrow">
                <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
            </div>
            <div class="thumb">
                <a href="#"><img class="img-fluid" src="{%static 'img/blog/next.jpg'%}" alt=""></a>
            </div>
        </div>
        {% endif %}



    </div>
</div>

core/templates/blog/include/blog-paginator.html
<nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
                                    {% if posts.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
                                    {% endif %}

                                {% for i in posts.paginator.page_range %}
                                    {% if posts.number == i %}
		                            <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                    {% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if posts.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
                                {%  endif %}
		                        </ul>
		                    </nav>

core/templates/blog/include/blog-popular-posts.html
{% load static %}
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
    {% for post in posts %}
<div class="single-post-list d-flex flex-row align-items-center">
    <div class="thumb">
        <img class="img-fluid" src="{{ post.image.url }}" alt="">
    </div>
    <div class="details">
        <a href="{% url 'blog:single' post_id=post.id %}"><h6>{{ post.title }}</h6></a>
{#        <p>{{ post.published_date|date:'d M Y' }}</p>#}
        <p>{{ post.published_date|naturaltime}}</p>
    </div>
</div>
        {% endfor %}
    </div>
</div>

core/templates/blog/include/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>

    <ul class="cat-list">
            {%for name, count in categories.items %}
        <li>
            <a href="{% url 'blog:blog_category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{ name }}</p>
                <p>{{ count }}</p>
            </a>
        </li>
				{% endfor %}
    </ul>
</div>

core/templates/blog/include/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:blog_search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

core/templates/blog/include/blog-writer.html
{%  load static %}
<div class="single-sidebar-widget user-info-widget">
    <img style="border-radius: 100%; width: 100px;" src="{{ account.image.url }}" alt="">
    <a href="#"><h4>{{ account.author }}</h4></a>
    <p>
        <a href="{% url 'accounts:profile'  %}" ><button href="" type="button" class="btn btn-primary">my account</button></a>
        {#{{ account.bio }}#}
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
	</ul>
	<p>
		{{ account.bio }}	</p>
</div>