core/blog/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/api/", views.PostListApiView.as_view(), name="post-list-api"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path(
        "post/<int:pk>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),

    # Cache
    path("test/", views.test, name="test"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse


# from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog Api",
        default_version="v1",
        description="this is a test api for maktabkhooneh project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="bigdeli.ali3@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

from django.views.generic import RedirectView
class indexView(RedirectView):
    pattern_name = 'blog:index'

# def indexView(request):
#     return HttpResponse("<h1>Django Final Test</h1>")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("comment/", include("comment.urls")),
    path("", indexView.as_view(), name="index"),
    path("blog/", include("blog.urls")),
    # path('api-docs/',include_docs_urls(title='api sample')),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'img/fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Travel</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
		</head>
		<body>
			<header id="header">
				<div class="header-top">
					<div class="container">
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>



                                {% if request.user.is_authenticated %}
			  					    <li><a href="#">{{ request.user.username }}</a></li>
			  					    <li><a href="{% url 'accounts:logout' %}" >logout</a></li>
                                {% else %}
                                    <li><a href="{% url 'accounts:singup' %}">singup</a></li>
			  					    <li><a href="{% url 'accounts:login' %}">login</a></li>
                                {% endif %}




			  				</ul>
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>
					</div>
				</div>
				<div class="container main-menu">
					<div class="row align-items-center justify-content-between d-flex">
				      <div >
				        <a href="{% url 'blog:index' %}"><img src="{% static 'img/logo1.png' %}" style="width: 100px;padding-left: 10px;border-left-width: 10px;margin-left: 10px;" alt="" title="" /></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li><a href="{% url 'blog:index' %}">Home</a></li>
				          <li><a href="{% url 'blog:index' %}">contact</a></li>
						  <li><a href="{% url 'blog:index' %}">About</a></li>
				          <li ><a href="{%  url 'blog:post-list' %}">Blog</a></li>

{#				          <li><a href="{% url 'website:contact' %}">Contact</a></li>#}
				        </ul>
				      </nav><!-- #nav-menu-container -->
					</div>
				</div>
			</header><!-- #header -->
            {% block content %}


            {% endblock %}
            	<!-- start footer Area -->
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="{% url 'blog:index' %}">Blog</a></li>
											<li><a href="">Contact</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.
								</p>
								<div id="mc_embed_signup">
									<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscription relative">
										<div class="input-group d-flex flex-row">
											<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
										</div>
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
 			<script src="{% static 'js/jquery-ui.js' %}"></script>
  			<script src="{% static 'js/easing.min.js' %}"></script>
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>
			<script src="{% static 'js/mail-script.js' %}"></script>
			<script src="{% static 'js/main.js' %}"></script>
		</body>
	</html>

core/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send message">
    </form>
</body>
</html>

core/templates/index.html
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row fullscreen align-items-center justify-content-between">
						<div class="col-lg-6 col-md-6 banner-left">
							<h6 class="text-white">Away from monotonous life</h6>
							<h1 class="text-white">Magical Travel</h1>
							<p class="text-white">
								If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.
							</p>

						</div>

					</div>
				</div>
			</section>
			<!-- End banner Area -->

			<!-- Start popular-destination Area -->
			<section class="popular-destination-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-70 col-lg-8">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Popular Destinations</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day.</p>
		                    </div>
		                </div>
		            </div>
					<div class="row">
						<div class="col-lg-4">
							<div class="single-destination relative">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<a href="#" class="price-btn">$150</a>
									<h4>Mountain River</h4>
									<p>Paraguay</p>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destination relative">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="">
								</div>
								<div class="desc">
									<a href="#" class="price-btn">$250</a>
									<h4>Dream City</h4>
									<p>Paris</p>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-destination relative">
								<div class="thumb relative">
									<div class="overlay overlay-bg"></div>
									<img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="">
								</div>
								<div class="desc">
									<a href="#" class="price-btn">$350</a>
									<h4>Cloud Mountain</h4>
									<p>Sri Lanka</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End popular-destination Area -->


			<!-- Start other-issue Area -->
			<section class="other-issue-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-70 col-lg-9">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Other issues we can help you with</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is.</p>
		                    </div>
		                </div>
		            </div>
					<div class="row">
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Rent a Car</h4>
								</a>
								<p>
									The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Cruise Booking</h4>
								</a>
								<p>
									I was always somebody who felt quite sorry for myself, what I had not got compared.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>To Do List</h4>
								</a>
								<p>
									The following article covers a topic that has recently moved to center stage–at least it seems.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
								</div>
								<a href="#">
									<h4>Food Features</h4>
								</a>
								<p>
									There are many kinds of narratives and organizing principles. Science is driven by evidence.
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- End other-issue Area -->





			<!-- Start home-about Area -->
			<section class="home-about-area">
				<div class="container-fluid">
					<div class="row align-items-center justify-content-end">
						<div class="col-lg-6 col-md-12 home-about-left">
							<h1>
								Did not find your Package? <br>
								Feel free to ask us. <br>
								We‘ll make it for you
							</h1>
							<p>
								inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.
							</p>
							<a href="#" class="primary-btn text-uppercase">request custom price</a>
						</div>
						<div class="col-lg-6 col-md-12 home-about-right no-padding">
							<img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="">
						</div>
					</div>
				</div>
			</section>
			<!-- End home-about Area -->


			<!-- Start blog Area -->
                {% comment %} {% latestposts %} {% endcomment %}
			<!-- End recent-blog Area -->


            {% endblock %}