core/blog/api/v1/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("post", views.PostModelViewSet, basename="post")
router.register("category", views.CategoryModelViewSet, basename="category")
router.register("comment", views.CommentModelViewSet, basename="comment")
urlpatterns = router.urls


# urlpatterns = [
#     # path('post/',views.postList,name="post-list"),
#     # path('post/<int:id>/',views.postDetail,name="post-detail"),
#     # path('post/',views.PostList.as_view(),name="post-list"),
#     # path('post/<int:pk>/',views.PostDetail.as_view(),name="post-detail"),
#     path('post/',views.PostViewSet.as_view({'get':'list','post':'create'}),name='post-list'),
#     path('post/<int:pk>/',views.PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}),name="post-detail"),
# ]

core/blog/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/api/", views.PostListApiView.as_view(), name="post-list-api"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path(
        "post/<int:pk>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),

    # Cache
    path("test/", views.test, name="test"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse


# from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog Api",
        default_version="v1",
        description="this is a test api for maktabkhooneh project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="bigdeli.ali3@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

from django.views.generic import RedirectView
class indexView(RedirectView):
    pattern_name = 'blog:index'

# def indexView(request):
#     return HttpResponse("<h1>Django Final Test</h1>")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("comment/", include("comment.urls")),
    path("", indexView.as_view(), name="index"),
    path("blog/", include("blog.urls")),
    # path('api-docs/',include_docs_urls(title='api sample')),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

# getting user model object
# User = get_user_model()


class Post(models.Model):
    """
    this is a class to define posts for blog app
    """

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE, related_name='upost')
    image = models.ImageField(upload_to='blog/',null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[0:5]

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    """
    this is a class to define categories for blog table
    """

    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "status", "category", "published_date", "image"]

core/blog/api/v1/views.py
from rest_framework.permissions import (
    IsAuthenticated,
    IsAuthenticatedOrReadOnly,
    IsAdminUser,
)
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework import viewsets
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework.decorators import action
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter

from .paginations import DefaultPagination
from .filters import PostFilters
from .serializers import PostSerializer, CategorySerializer
from ...models import Post, Category
from .permissions import IsOwnerOrReadOnly


from comment.models import Comment
from comment.api.v1.serializers import CommentSerializer


class PostModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    # filterset_fields = {'category':["exact","in"], 'author':["exact"],'status':["exact"]}
    filterset_class = PostFilters
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

class CommentModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination

core/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import (
    ListView,
    DetailView,
    FormView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.http import HttpResponse, JsonResponse
from .models import Post
from django.shortcuts import get_object_or_404
from .forms import PostForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)

# test
from django.views import View
from comment.models import Comment
from django.contrib import messages
from comment.forms import CommentForm
from accounts.models import Profile
from accounts.models import User
import requests
# Create your views here.

# Function Base View show a template

class IndexView(TemplateView):
    """
    a class based view to show index page
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        return context


class PostListView(ListView):
    permission_required = "blog.view_post"
    # queryset = Post.objects.all()
    # model = Post
    context_object_name = "posts"
    # paginate_by = 2
    ordering = "-id"
    def get_queryset(self):
        posts = Post.objects.filter(status=True)
        return posts


class PostDetailView(View):
    form_class = CommentForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['pk'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        commments = Comment.objects.filter(post=self.post_instance.id)
        return render(request, 'blog/blog-single.html',{'post':self.post_instance,'commments':commments, 'form':self.form_class})


    def post(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comments = form.save(commit=False)
            new_comments.user = profile
            new_comments.name = request.user
            new_comments.post = self.post_instance
            new_comments.save()
            messages.success(request, 'your comment submitted successfully', 'success')
            return redirect('blog:post-detail', self.post_instance.id)
        return redirect('blog:post-detail', self.post_instance.id)


class PostListApiView(TemplateView):
    template_name = "blog/post_list_api.html"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.author = profile
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = "/blog/post/"

# @cache_page(60)
# def test(request):
#     response = requests.get("https://5add16cb-13b5-4c3e-ac48-635ec4f8654b.mock.pstmn.io/test/delay/20")
#     return JsonResponse(response.json())

@cache_page(1200)
def test(request):
    api_key = 'c10cf61f23551c490fe69ca601a58502'
    city_name = 'Tehran'
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}&units=metric"

    response = requests.get(url)
    data = response.json()

    if data['cod'] == 200:
        temperature = data['main']['temp']
        weather_description = data['weather'][0]['description']
        print(f"The temperature in {city_name} is {temperature} degrees Celsius with {weather_description}.")
        return JsonResponse(response.json())
    else:
        return HttpResponse("Failed to retrieve weather data.")

    

core/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
			<!-- start banner Area -->
			<section class="relative about-banner" >
{#				<div class="overlay overlay-bg"><img style="filter: blur(8px); zoom: revert; height: 120%; width: 100%;" class="img-fluid " src="{{ post.image.url }}"></div>#}
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{ post.title }}
							</h1>	
							<p class="text-white link-nav"><a href="{% url 'blog:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span>{{ post.title }}</p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{ post.image.url }}" alt="">
									</div>
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
{#                                        {% for category in post.category.all %}#}
{#										<li><a href="#">{{ category.name }},</a></li>#}
{#                                         {% endfor %}#}
                                    {{ post.category.all|join:", " }}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author.username }}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:'D d M Y' }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title }}</h3>
									<p class="excert">
									{{ post.content|safe }}
                                    </p>
								</div>
                                {% if request.user.is_authenticated %}
								<a href="{% url 'blog:post-edit' pk=post.id %}" ><button style="margin: 6px;" type="button" class="btn btn-primary">edite</button></a>
								<a href="{% url 'blog:post-delete' pk=post.id %}" ><button style="margin: 6px;" type="button" class="btn btn-danger">delete</button></a>
                                {% endif %}
							</div>
                            <div class="navigation-area">
								<div class="row">

                                    {% if prev_post %}
                                        {% for prevpost in prev_post %}
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										<div class="thumb">
											<a href="{% url 'blog:single' post_id=prevpost.id %}"><img class="img-fluid" style="width: 100px" src="{{ prevpost.image.url }}" alt=""></a>
										</div>
										<div class="arrow">
											<a href="{% url 'blog:single' post_id=prevpost.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="detials">
											<p>Prev Post</p>
											<a href="{% url 'blog:single' post_id=prevpost.id %}"><h4>{{ prevpost.title }}</h4></a>
										</div>
									</div>
                                        {% endfor %}
                                    {% endif %}

                                    {% if next_post %}
                                        {% for nextpost in next_post %}
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										<div class="detials">
											<p>Next Post</p>
											<a href="{% url 'blog:single' post_id=nextpost.id %}"><h4>{{ nextpost.title }}</h4></a>
										</div>
										<div class="arrow">
											<a href="{% url 'blog:single' post_id=nextpost.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
										</div>
										<div class="thumb">
											<a href="{% url 'blog:single' post_id=nextpost.id %}"><img class="img-fluid" style="width: 100px;" src="{{ nextpost.image.url }}" alt=""></a>
										</div>
									</div>
                                        {% endfor %}
                                    {% endif %}




								</div>
							</div>
                            {#{% include 'blog/include/blog-navigation-area.html' %}#}
                            {% include 'blog/include/blog-comments.html' %}


						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								

                                {% include 'blog/include/blog-writer.html' %}
                                {% comment %} {% latestposts %} {% endcomment %}


								<div class="single-sidebar-widget popular-post-widget">


                                    {% comment %} {% postCategories %} {% endcomment %}
								{% include 'blog/include/blog-cat-tag.html' %}
							</div>



						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
		{% endblock %}

core/templates/blog/post_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static "css/create-edite.css" %}" rel="stylesheet">
    <title>Create Post</title>
</head>
<body>
 <div class="form-body">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>post</h3>
                        <p >{{ form.errors }}</p>
                        <form class="requires-validation" method="post" >
                            {% csrf_token %}
                            <p>Are you sure you want to delete "{{ object }}"?</p>
                            <div class="form-button mt-3">
                                <button type="submit" value="Confirm" class="btn btn-danger">delete</button>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div> 
    
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{object.title}}</h1>
    <hr>
    <small>{{object.author}} - {{object.published_date}} </small>
    <p>{{object.content}}</p>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    
</body>
</html>

core/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Walk on the path of becoming God
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/js-wallpaper.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">JavaScript</h4>
								        <span></span>								        
								        <p>Enjoy your programing life</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/react-wallpaper.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">react</h4>
								        <span></span>								        
								        <p>power and fast</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/python-wallpaper.jpg'%}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">python</h4>
								        <span></span>
								        <p>The future is under your control</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
                            {% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
                                        {% for category in post.category.all %}
										<li><a href="{% url 'blog:blog_category' cat_name=category %}">{{ category.name }}</a>{% if not forloop.last %},{% endif %} </li>
                                         {% endfor %}
{#                                        <li><a href="">{{ post.category.all|join:", " }}</a></li>#}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published_date|date:'D d M Y' }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{post.pcomments.count}}</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{ post.image.url }}" alt="">
									</div>
									<a class="posts-title" href="#"><h3>{{ post.title }}</h3></a>
									<p class="excert">
									{{ post.content|truncatechars:200|safe }}
                                    </p>
									<a href="{% url 'blog:post-detail' pk=post.id  %}" class="primary-btn">View More</a>
								</div>
							</div>
                            {% endfor %}
		                      {% include 'blog/include/blog-paginator.html' %}
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
                                {% comment %} {%  include 'blog/include/blog-search.html' %} {% endcomment %}
								{% include 'blog/include/blog-writer.html' %}
								{% comment %} {% latestposts %} {% endcomment %}


								{% comment %} {% postCategories %} {% endcomment %}
                                {% comment %} {% include 'blog/include/blog-all-tags.html' %} {% endcomment %}


							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
	{% endblock %}

core/templates/blog/post_list_api.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>blog posts</h1>
    <ol id="post-wrapper">

        <!-- <li>
            <a href="" ><h2> - </h2></a>
        </li> -->

    </ol>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $.get('/blog/api/v1/post/',  // url
            function (data, textStatus, jqXHR) { 
                wrapper = $('#post-wrapper');
                for (post of data.results){
                    wrapper.append(`<li><a href="${post.absolute_url}"><h2>${post.title}</h2></a></li>`)
                }
                
                // alert('status: ' + textStatus + ', data:' + data);
                // console.log(data);

            });
    </script>

</body>

</html>